[package]
name = "brainlove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
colored = "2.0.0"
rustyline = "10.1.0"
yew = { version = "0.20.0", features = ["csr"] }
